# Generated by Django 3.2.18 on 2023-05-24 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.TextField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField(null=True)),
                ('release_date', models.TextField(null=True)),
                ('director', models.TextField()),
                ('trailer_key', models.TextField(null=True)),
                ('vote_average', models.TextField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
