# Generated by Django 3.2.18 on 2023-05-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.TextField()),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('release_date', models.DateField(null=True)),
                ('director', models.TextField()),
                ('trailer_key', models.TextField(null=True)),
                ('vote_average', models.TextField()),
            ],
        ),
    ]
