# Generated by Django 3.2.18 on 2023-05-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_title',
        ),
    ]
